In [1]:
from __future__ import print_function
import torch

未初始化的矩阵数值取决于内存情况

In [2]:
x = torch.empty(5, 3)
print(x)

tensor([[-1.4751e-28,  4.5799e-41,  1.5431e+21],
        [ 3.0754e-41, -1.4750e-28,  4.5799e-41],
        [-1.4750e-28,  4.5799e-41,  4.5439e+30],
        [ 2.0283e-19,  4.4647e+30,  6.9987e+22],
        [ 7.8675e+34,  1.3563e-19,  3.0304e+35]])


随机初始化

In [3]:
x = torch.rand(5, 3)
print(x)

tensor([[0.3170, 0.3080, 0.0711],
        [0.1714, 0.9206, 0.9772],
        [0.2669, 0.1404, 0.6494],
        [0.8921, 0.8090, 0.1666],
        [0.0289, 0.0952, 0.0224]])


0 初始化


In [4]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


指定数据构建

In [5]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


模板构建

In [6]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                                      # result has the same size

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-0.7566, -0.2797, -0.1174],
        [ 0.0496,  0.7225, -1.3467],
        [ 0.4956,  0.4326, -1.1981],
        [ 0.5965,  0.6773, -1.1201],
        [ 1.4410,  1.0451,  1.4229]])


张量形状

In [7]:
print(x.size())

torch.Size([5, 3])


加法1

In [8]:
y = torch.rand(5, 3)
print(x + y)

tensor([[-0.7310,  0.5311,  0.0193],
        [ 0.7256,  1.4681, -0.9721],
        [ 0.5406,  0.5714, -1.1565],
        [ 1.2949,  1.2453, -0.7157],
        [ 2.2764,  1.8528,  2.0020]])


加法2

In [9]:
print(torch.add(x, y))

tensor([[-0.7310,  0.5311,  0.0193],
        [ 0.7256,  1.4681, -0.9721],
        [ 0.5406,  0.5714, -1.1565],
        [ 1.2949,  1.2453, -0.7157],
        [ 2.2764,  1.8528,  2.0020]])


指定输出数据位置

In [10]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[-0.7310,  0.5311,  0.0193],
        [ 0.7256,  1.4681, -0.9721],
        [ 0.5406,  0.5714, -1.1565],
        [ 1.2949,  1.2453, -0.7157],
        [ 2.2764,  1.8528,  2.0020]])


就地输出数据


In [11]:
# adds x to y
y.add_(x)
print(y)

tensor([[-0.7310,  0.5311,  0.0193],
        [ 0.7256,  1.4681, -0.9721],
        [ 0.5406,  0.5714, -1.1565],
        [ 1.2949,  1.2453, -0.7157],
        [ 2.2764,  1.8528,  2.0020]])


截取数据

In [12]:
print(x[:, 1])

tensor([-0.2797,  0.7225,  0.4326,  0.6773,  1.0451])


改变张量形状

In [13]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


张量转 python 数字

In [14]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-0.3807])
-0.3806738257408142


张量转numpy，共享内存

In [15]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [16]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [17]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


NumPy Array 转张量


In [18]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


GPU计算
